run_name: "test_one"

### THRESHOLDS ###

assemble_thresh: 0.95
cluster_nuc_id: 0.95
cluster_overlap: 0.9
min_contig_length: 200

### DIRECTORIES, FILE LOCATIONS ###

spades_path: "/home/biller/software/SPAdes-3.15.5-Linux/bin/"
prod_path: "/nobackup1/chisholmlab/software/Prodigal"
quast_path: "/pool001/biller/databases/quast"
nextflow_path: "/nobackup1/biller/gray"
gorg_path: "/nobackup1/biller/gray/gorg-classifier"
krona_nodes_dmp: "resources/NCBI/nodes2.dmp"
krona_names_dmp: "resources/NCBI/names2.dmp"
cluster_db: "NA"

### METHODS ###

quast_method: "metaQUAST"
assembly_method: "metaspades"
prodigal_meth: "meta_comp"
mmseq_cluster_method: "easy_cluster"

### COMPUTING RESOURCES ###

threads: 20
spades_py_memory: 250

### FOR MEMORY - SAVING PURPOSES ###


#ASSEMBLY PRODUCTS
rm1_files: "config/rm1_files.txt"

#CLUSTER PRODUCTS
rm2_files: "config/rm2_files.txt"

#COVERAGE
coverage_of_what: "results/assembled_seqs/contigs.fasta"

#COMPARE
do_compare: TRUE

#COVERAGE INPUTS
vesicle_subset_illumina_covr_inp: "results/03-assembled_seqs/cellular_subset_assembly/contigs.fasta"
vesicle_subset_all_covr_inp: "ERROR"
cellular_subset_covr_inp: "results/01-documentation/cellular_subset_documentation.txt"
vesicle_subset_nanopore_covr_inp: "results/03-assembled_seqs/cellular_subset_assembly/contigs.fasta"
