run_name: "test_one"

### THRESHOLDS ###

assemble_thresh: 0.95
ORF_thresh: "value here"
cluster_thresh: "value here"
compare_thresh: "value here"

### DIRECTORIES, FILE LOCATIONS ###

trimmed_fastq_fwd_loc_list: "/nobackup1/billerlab/gray/data_GP/subset_fwd.fastq.gz"
trimmed_fastq_bwd_loc_list: "/nobackup1/billerlab/gray/data_GP/subset_bwd.fastq.gz"
spades_path: "/home/billerlab/software/SPAdes-3.15.5-Linux/bin/"
prod_path: "/nobackup1/chisholmlab/software/Prodigal"

### METHODS ###

assembly_meth: "metaspades"
prodigal_meth: "meta"

### COMPUTING RESOURCES ###

threads: 20
spades_py_memory: 250




