run_name: "test_one"

### THRESHOLDS ###

assemble_thresh: 0.95
ORF_thresh: "value here"
cluster_thresh: "value here"
compare_thresh: "value here"

### DIRECTORIES, FILE LOCATIONS ###

final_report_loc: "/home/billerlab/gray/genPride/results/final_report.txt"
trimmed_fastq_fwd_loc_list: ["/home/billerlab/gray/data_GP/test_fwd.fastq.gz"]
trimmed_fastq_bwd_loc_list: ["/home/billerlab/gray/data_GP/test_bwd.fastq.gz"]

### METHODS ###

assembly_meth: "metaspades"
   #options: "metaspades"

### COMPUTING RESOURCES ###

nodes: 1
cpus: 20
memory: 250000
runtime: 2-00:00:00
partition: "put here"
ex_need: "exclusive"



