run_name: "test_one"
final_output: "results/slurm_gorg.out"

### THRESHOLDS ###

assemble_thresh: 0.95
cluster_nuc_id: 0.95
cluster_overlap: 0.9

### DIRECTORIES, FILE LOCATIONS ###

trimmed_fastq_fwd_loc_list: "/nobackup1/biller/gray/data_GP/subset_fwd.fastq.gz"
trimmed_fastq_bwd_loc_list: "/nobackup1/biller/gray/data_GP/subset_bwd.fastq.gz"
spades_path: "/home/biller/software/SPAdes-3.15.5-Linux/bin/"
prod_path: "/nobackup1/chisholmlab/software/Prodigal"
quast_path: "/nobackup1/biller/gray/quast"
nextflow_path: "/nobackup1/biller/gray"
gorg_path: "/nobackup1/biller/gray/gorg-classifier"

### METHODS ###

assembly_meth: "metaspades"
prodigal_meth: "meta_comp"
mmseq_cluster_method: "easy_cluster"
mmseqs2_database: "INSERT HERE"
quast_method: "metaQUAST"
classifier: "GORG"

### COMPUTING RESOURCES ###

threads: 20
spades_py_memory: 250

### FOR MEMORY - SAVING PURPOSES ###

#ASSEMBLY PRODUCTS
rm1_files: "config/rm1_files.txt"   

#CLUSTER PRODUCTS
rm2_files: "config/rm2_files.txt"

